<template>
    <div class="mx-auto py-20 flex min-h-screen w-fit flex-col items-center justify-center px-10">
        <div class="inline-block w-14 text-4xl">
            <img src="/chat.png" alt="" srcset="" />
        </div>
        <p class="my-2 text-2xl font-bold">ChatGPT Anti-Inspector</p>
        <p>
            <em class="text-sm opacity-75"
                >An encryption algorithm used to counter GPT Inspector, which can "humanize" the text generated by
                GPT.</em
            >
        </p>
        <div class="w-full max-w-2xl py-4">
            <n-input
                type="textarea"
                :autosize="{
                    minRows: 1,
                }"
                placeholder="What's your text?"
                v-model:value="text"
            >
            </n-input>
            <p v-if="ans" class="text-slate-400">
                <p class="text-sm opacity-75 font-bold mt-3 mb-1 text-slate-500">Result:</p>
                {{ ans }}
            </p>
        </div>
        <div class="m-3">
            <n-button @click="humanize">{{ isCompleted ? 'Try again':'Humanize'  }}</n-button>
        </div>
    </div>
</template>
<script setup>
import axios from 'axios';
const isCompleted = ref(false);
const text = ref('');
const ans = ref(null);
const humanize = async () => {
    if (isCompleted.value) {
        text.value = '';
        ans.value = null;
        isCompleted.value = false;
        return;
    }
    const data = await request(text.value);
    ans.value = data;
    isCompleted.value = true;
};

const request = async (text) => {
    // test without api
    console.log(text);
    return 'Hello World';

    // test with api
    /* const { data } = await axios.post('https://localhost:1234/encrypt', {
        text,
    });
    return data; */
};
</script>
